BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "User" (
	"Id"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Solved"	INTEGER,
	"Score"	INTEGER,
	"HideSolved"	BOOLEAN,
	PRIMARY KEY("Id")
);
CREATE TABLE IF NOT EXISTS "Quotes" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Quote"	TEXT NOT NULL,
	"Type"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "Puzzle" (
	"Code"	TEXT NOT NULL UNIQUE,
	"Points"	INTEGER,
	PRIMARY KEY("Code")
);
CREATE TABLE IF NOT EXISTS "PuzzleData" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"PuzzleCode"	TEXT NOT NULL,
	"Type"	INTEGER NOT NULL,
	"Data"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "CompletedPuzzles" (
	"UserId"	TEXT NOT NULL,
	"PuzzleCode"	TEXT NOT NULL,
	"DateCompleted"	DATETIME,
	FOREIGN KEY("UserId") REFERENCES "User"("Id") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("PuzzleCode") REFERENCES "Puzzle"("Code") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("UserId","PuzzleCode")
);
COMMIT;
